### ISSUE TITLE
Use updated fast Owen hash.

### ISSUE THREAD

**Issue by cessen** [tylermorganwall/spacefillr#1]
Looking at `sobol.h`, it appears that you're using the old hash from my post https://psychopath.io/post/2021_01_30_building_a_better_lk_hash

I'm really glad you're using it, by the way!  No problem with that at all--that's why I blogged about it.  However, someone found a potentially serious problem with those hashes.  I've fixed the problem in a new hash, which I've included in an update to the blog post, along with an explanation of the problem and the fix.

Anyway, here's the new hash:

```
x ^= x * 0x3d20adea
x += seed
x *= (seed >> 16) | 1
x ^= x * 0x05526c56
x ^= x * 0x53a22864
```

It's much better, and I strongly recommend switching to it.

**Comment by tylermorganwall** [comment]
Good to know! I do see a significant improvement in convergence with the new hash. Thanks for the update and nice work!

Old:
![oldhash](https://user-images.githubusercontent.com/297609/123734575-981bef80-d86b-11eb-9e16-6b290c6e10db.png)

New:
![newhash](https://user-images.githubusercontent.com/297609/123734583-99e5b300-d86b-11eb-8f7c-ff89ce3b57dd.png)

**Comment by cessen** [comment]
Those results are great!  Glad it was useful!
